/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package airportproject;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.PrintStream;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author IMOE001
 */
public class AirPortGUI extends javax.swing.JFrame {

    /**
     * Creates new form AirPortGUI
     */
    public AirPortGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightNo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        finishFlights = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        routeA_TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        routeB_TextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        routeC_TextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        routeD_TextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME TO THE AIR PORT");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(242, 250, 255));
        jPanel1.setFocusable(false);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("start");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\IMOE001\\Desktop\\AirPort\\d.png")); // NOI18N

        FlightNo.setColumns(20);
        FlightNo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        FlightNo.setForeground(new java.awt.Color(0, 0, 153));
        FlightNo.setRows(1);
        jScrollPane1.setViewportView(FlightNo);

        finishFlights.setColumns(4);
        finishFlights.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finishFlights.setForeground(new java.awt.Color(51, 0, 153));
        finishFlights.setRows(1);
        finishFlights.setTabSize(4);
        finishFlights.setMinimumSize(new java.awt.Dimension(2, 29));
        jScrollPane2.setViewportView(finishFlights);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Waiting");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Finish");

        routeA_TextArea.setBackground(new java.awt.Color(255, 255, 204));
        routeA_TextArea.setColumns(20);
        routeA_TextArea.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        routeA_TextArea.setRows(1);
        routeA_TextArea.setName("routeA"); // NOI18N
        jScrollPane3.setViewportView(routeA_TextArea);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\IMOE001\\Desktop\\AirPort\\c.png")); // NOI18N

        routeB_TextArea.setBackground(new java.awt.Color(255, 255, 204));
        routeB_TextArea.setColumns(20);
        routeB_TextArea.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        routeB_TextArea.setRows(1);
        routeB_TextArea.setName("routeA"); // NOI18N
        jScrollPane4.setViewportView(routeB_TextArea);

        routeC_TextArea.setBackground(new java.awt.Color(255, 255, 204));
        routeC_TextArea.setColumns(20);
        routeC_TextArea.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        routeC_TextArea.setRows(1);
        routeC_TextArea.setName("routeA"); // NOI18N
        jScrollPane5.setViewportView(routeC_TextArea);

        routeD_TextArea.setBackground(new java.awt.Color(255, 255, 204));
        routeD_TextArea.setColumns(20);
        routeD_TextArea.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        routeD_TextArea.setRows(1);
        routeD_TextArea.setToolTipText("");
        routeD_TextArea.setName("routeA"); // NOI18N
        jScrollPane6.setViewportView(routeD_TextArea);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel3.setText("B");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel4.setText("A");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel5.setText("D");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel6.setText("C");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         

        RunWays runWay1=new RunWays("A", 9990,routeA_TextArea);
        RunWays runWay2=new RunWays("B", 8787,routeB_TextArea);
        RunWays runWay3=new RunWays("C", 6787,routeC_TextArea);
        RunWays runWay4=new RunWays("D", 10000,routeD_TextArea);

        runWay1.AddItemToDistancesDictionay(Directions.NORTH, 13);
        runWay1.AddItemToDistancesDictionay(Directions.WEST, 35);
        runWay1.AddItemToDistancesDictionay(Directions.EAST, 12);
        runWay1.AddItemToDistancesDictionay(Directions.SOUTH, 13);
        runWay1.AddItemToDistancesDictionay(Directions.NORTH_EAST, 6);
        runWay1.AddItemToDistancesDictionay(Directions.NORTH_WEST, 3);
        runWay1.AddItemToDistancesDictionay(Directions.SOUTH_EAST, 23);
        runWay1.AddItemToDistancesDictionay(Directions.SOUTH_WEST, 65);

        runWay2.AddItemToDistancesDictionay(Directions.NORTH, 13);
        runWay2.AddItemToDistancesDictionay(Directions.WEST, 56);
        runWay2.AddItemToDistancesDictionay(Directions.EAST, 12);
        runWay2.AddItemToDistancesDictionay(Directions.SOUTH, 43);
        runWay2.AddItemToDistancesDictionay(Directions.NORTH_EAST, 65);
        runWay2.AddItemToDistancesDictionay(Directions.NORTH_WEST, 2);
        runWay2.AddItemToDistancesDictionay(Directions.SOUTH_EAST, 3);
        runWay2.AddItemToDistancesDictionay(Directions.SOUTH_WEST, 5);

        runWay3.AddItemToDistancesDictionay(Directions.NORTH, 3);
        runWay3.AddItemToDistancesDictionay(Directions.WEST, 54);
        runWay3.AddItemToDistancesDictionay(Directions.EAST, 2);
        runWay3.AddItemToDistancesDictionay(Directions.SOUTH, 3);
        runWay3.AddItemToDistancesDictionay(Directions.NORTH_EAST, 78);
        runWay3.AddItemToDistancesDictionay(Directions.NORTH_WEST, 20);
        runWay3.AddItemToDistancesDictionay(Directions.SOUTH_EAST, 13);
        runWay3.AddItemToDistancesDictionay(Directions.SOUTH_WEST, 25);

        runWay4.AddItemToDistancesDictionay(Directions.NORTH, 13);
        runWay4.AddItemToDistancesDictionay(Directions.WEST, 56);
        runWay4.AddItemToDistancesDictionay(Directions.EAST, 56);
        runWay4.AddItemToDistancesDictionay(Directions.SOUTH, 14);
        runWay4.AddItemToDistancesDictionay(Directions.NORTH_EAST, 6);
        runWay4.AddItemToDistancesDictionay(Directions.NORTH_WEST, 9);
        runWay4.AddItemToDistancesDictionay(Directions.SOUTH_EAST, 1);
        runWay4.AddItemToDistancesDictionay(Directions.SOUTH_WEST, 8);

        airPort.AddRunWay(runWay1);
        airPort.AddRunWay(runWay2);
        airPort.AddRunWay(runWay3);
        airPort.AddRunWay(runWay4);

        Flights.waitingFlightsTextArea=new PrintStream(new CustomOutputStream(FlightNo));
        Flights.finishedFlightsTextArea=new PrintStream(new CustomOutputStream(finishFlights));

        Flights flight1=new Flights("1", Directions.NORTH, Action.LAND, airPort);
        Flights flight2=new Flights("2", Directions.EAST, Action.TAKE_OFF, airPort);
        Flights flight3=new Flights("3",Directions.SOUTH_WEST, Action.TAKE_OFF, airPort);
        Flights flight4=new Flights("4",Directions.NORTH, Action.TAKE_OFF, airPort);
        Flights flight5=new Flights("5", Directions.WEST, Action.LAND, airPort);
        Flights flight6=new Flights("6",Directions.SOUTH, Action.TAKE_OFF, airPort);
        Flights flight7=new Flights("7",Directions.NORTH_WEST, Action.LAND, airPort);

        airPort.AddFlight(flight1);
        airPort.AddFlight(flight2);
        airPort.AddFlight(flight3);
        airPort.AddFlight(flight4);
        airPort.AddFlight(flight5);
        airPort.AddFlight(flight6);
        airPort.AddFlight(flight7);

    }
   
        AirPort airPort=new AirPort("BEN-GURION-AIRPORT");

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirPortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirPortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirPortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirPortGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
               AirPortGUI airPortGUI=new AirPortGUI();
               airPortGUI.setVisible(true);  
               airPortGUI.pack();
            }
        });

    }
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea FlightNo;
    private javax.swing.JTextArea finishFlights;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea routeA_TextArea;
    private javax.swing.JTextArea routeB_TextArea;
    private javax.swing.JTextArea routeC_TextArea;
    private javax.swing.JTextArea routeD_TextArea;
    // End of variables declaration//GEN-END:variables
}
